import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const COOKIE_NAME_RE = /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;

export type CookiePair = { name: string; value: string };

/** Prefer server cookies file when set. */
export function serverCookiesPath(): string | undefined {
  const path = process.env.YTDLP_COOKIES_FILE?.trim();
  return path || undefined;
}

/**
 * Parse a Cookie header or semicolon-separated pairs into name/value entries.
 * Rejects oversized payloads and invalid names.
 */
export function parseCookieHeader(raw: string | undefined | null): CookiePair[] {
  if (!raw?.trim()) return [];

  if (raw.length > 16_384) {
    throw new Error("Cookie payload is too large.");
  }

  const pairs: CookiePair[] = [];
  for (const part of raw.split(";")) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const name = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (!COOKIE_NAME_RE.test(name)) continue;
    if (!value) continue;
    pairs.push({ name, value });
  }

  return pairs;
}

/** Build Netscape cookies.txt content for Instagram (domain .instagram.com). */
export function toNetscapeCookies(
  pairs: CookiePair[],
  domain = ".instagram.com",
): string {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by ReelSave"];
  const expires = Math.floor(Date.now() / 1000) + 60 * 60 * 24;

  for (const { name, value } of pairs) {
    // domain, includeSubdomains, path, secure, expires, name, value
    lines.push(
      [domain, "TRUE", "/", "TRUE", String(expires), name, value].join("\t"),
    );
  }

  return `${lines.join("\n")}\n`;
}

export type EphemeralCookies = {
  path: string;
  cleanup: () => Promise<void>;
};

/** Write cookies to a temp file; caller must cleanup(). */
export async function writeEphemeralCookies(
  pairs: CookiePair[],
): Promise<EphemeralCookies | null> {
  if (pairs.length === 0) return null;

  const dir = await mkdtemp(join(tmpdir(), "reelsave-cookies-"));
  const path = join(dir, "cookies.txt");
  await writeFile(path, toNetscapeCookies(pairs), { mode: 0o600 });

  return {
    path,
    cleanup: async () => {
      await rm(dir, { recursive: true, force: true }).catch(() => undefined);
    },
  };
}

/**
 * Resolve which cookies file yt-dlp should use.
 * Request cookies win when present; otherwise fall back to YTDLP_COOKIES_FILE.
 */
export async function resolveCookiesFile(
  cookieHeader: string | undefined | null,
): Promise<{ path?: string; cleanup: () => Promise<void> }> {
  const pairs = parseCookieHeader(cookieHeader);
  if (pairs.length > 0) {
    const ephemeral = await writeEphemeralCookies(pairs);
    if (ephemeral) {
      return { path: ephemeral.path, cleanup: ephemeral.cleanup };
    }
  }

  return {
    path: serverCookiesPath(),
    cleanup: async () => undefined,
  };
}
